### ISSUE TITLE
Is it possible to create sliders?

### ISSUE THREAD

**Issue by Superkat32** [TeamMidnightDust/MidnightLib#15]
Is it possible to create a slider(like the FOV or the brightness slider) with MidnightLib? I don't see anything on the wiki, but I wanted to make sure that I wasn't missing something.
Thanks in advance!

**Comment by Motschen** [comment]
Currently it's not possible, though I might implement it in the future if it doesn't increase file size too heavily.

**Comment by Motschen** [comment]
Added in 1.0.0, thanks for the suggestion!
