### ISSUE TITLE
Crash if an integer inputted into the text box is greater than max int.

### ISSUE THREAD

**Issue by MasterToster** [TeamMidnightDust/MidnightLib#16]
As the title states.
Suggested fix: i just changed the line 149 in MidnightConfig.java from
`
                    value = f.apply(s);`
to
`try{
                    value = f.apply(s);
                } catch(NumberFormatException e){
                    return false;
                }`

**Comment by Motschen** [comment]
I'll look into this, but I'll try to ensure users aren't able to input integers over the int limit in the first place.
