### ISSUE TITLE
1.19.2 quilt/fabric Client crash Incompatibility with nyf's spiders.

### ISSUE THREAD

**Issue by netcore10** [TeamMidnightDust/MidnightLib#18]
Nyf's spider's issues lead to an invalid discord link, my ownly option was to send one here.
https://mclo.gs/7JJELGb
[crash-2022-12-03_18.34.31-client.txt](https://github.com/TeamMidnightDust/MidnightLib/files/10147124/crash-2022-12-03_18.34.31-client.txt)
Can you shed some light on the problem?

**Comment by Motschen** [comment]
That issue is caused by Moonlight Lib, MidnightLib has nothing to do with it.

**Comment by netcore10** [comment]
Oops! My bad, mixed up the mods!
