### ISSUE TITLE
MidnightConfig suggestion - `@RequiresRestart`

### ISSUE THREAD

**Issue by triphora** [TeamMidnightDust/MidnightLib#20]
An annotation which, when a config option is set with it, prompts the user to either restart or continue playing without the value actually changed.

**Comment by Motschen** [comment]
This would actually be quite hard (if not impossible) with the current way saving values is implemented and changing the way saving is handled, as well as creating that prompt would increase file size quite heavily.
In my opinion, just stating it in the tooltip would be enough for most people.
