### ISSUE TITLE
Request: Tabs for config

### ISSUE THREAD

**Issue by MrSam7K** [TeamMidnightDust/MidnightLib#21]
Perhaps we could get tabs for config so everything could be more organized?

**Comment by Motschen** [comment]
With the new tabbed buttons being added in 1.19.4, I'll see if I can find a way to implement tabs while keeping the file size as small as possible.

**Comment by Motschen** [comment]
I did a thing...
![image](https://user-images.githubusercontent.com/49783724/223805993-548cac7a-9c1e-4b18-a7cd-f134295b9171.png)

**Comment by Motschen** [comment]
Added in 1.2.0 :)
