### ISSUE TITLE
Crashes on 1.19.3 in dev

### ISSUE THREAD

**Issue by CammiePone** [TeamMidnightDust/MidnightLib#23]
MidnightLib: 1.1.0
Minecraft: 1.19.3
Quilt Loader: 0.18.1-beta.64
QFAPI: 5.0.0-beta.4+0.73.0

![image](https://user-images.githubusercontent.com/16853086/215590089-84430031-8cef-4100-b838-c7c3581646b5.png)

**Comment by Motschen** [comment]
Just replaced the file on modrinth with a fixed version, since this doesn't affect users.
Clean your gradle cache and reload gradle to receive the fix.
Sorry for the long delay.
