### ISSUE TITLE
Translation handling for "Reset"

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [TeamMidnightDust/MidnightLib#25]
I found that string "Reset" unavailable for translation in en_us.json

![image](https://user-images.githubusercontent.com/51203385/221396877-13bb2f66-5cb7-40df-8e64-c6956f5d3236.png)
_This is a demonstation of fully translated library into Tatar language that I submitted earlier (#24)_

Possible solutions:
You can add own translation for it (i. e. add this string as translatable in en_us.json, but I think that the second one solution is better than this)...
Or use it from Vanilla strings (For example, this string appears in "Key Binds" and has the same size as this button).

**Comment by Motschen** [comment]
This is actually by choice, as some equivalents for the word "reset" (like "zurücksetzen" in German) would easily exceed the button. The text also gets shortened to just "R" on list and color fields, which would be confusing if the language's equivalent doesn't start with R. Basically everyone knows what reset means, so I don't think this is a particularly big issue.

**Comment by Motschen** [comment]
I'm leaving this open though, in case someone comes up with a better solution.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
↻
