### ISSUE TITLE
stray \n somewhere in quilt.mod.json

### ISSUE THREAD

**Issue by Merith-TK** [TeamMidnightDust/MidnightLib#28]
I was making a tool that automatically parses mod.json in jars to automatically remove duplicates, and I ran into an wierd issue decoding the json 
```
$ go run .
2023/04/16 17:05:36 ./mods/midnightlib-quilt-1.3.0.jar
2023/04/16 17:05:36 [DECODE QUILT MOD] invalid character '\n' in string literal
```

I was able to manually fix it by removing all `\n` characters in the json and reformatting, figured I would inform you

**Comment by Merith-TK** [comment]
found it
![image](https://user-images.githubusercontent.com/10422110/232351583-f6bae87a-feb5-4c6f-8973-1cc2e233bf3c.png)
ripped straight from the mod.json

manually patching mod json to have an proper `\n` there fixes it (as shown by here, filename is only printed if there is an error decoding json)
![image](https://user-images.githubusercontent.com/10422110/232351821-0943f706-4a64-4a12-b917-f3a8d18ff97e.png)

**Comment by Motschen** [comment]
How would I insert a proper \n character?

**Comment by Merith-TK** [comment]
Sorry I didnt reply here but it looks like the *compiler* is incorrectly converting the escaped `\n` into a literal, for some reason, will see if I still have my tool for it so you can take a look at how I discovered this
