### ISSUE TITLE
quilt_base missing

### ISSUE THREAD

**Issue by Nitron-picarla** [TeamMidnightDust/MidnightLib#30]
im probably just missing something super obvious, but im using quilt 1.19.2 and midnightlib 1.0.0 for quilt 1.19.2 and i get the error of missing dependency quilt_base. however, this is the first im hearing of this file and because of its simple name im not getting any actual results from google or anything. where on earth do i find this? i have no idea where else to ask, so sorry if this shouldn't be here.

**Comment by ghost** [comment]
Check [this](https://www.curseforge.com/minecraft/mc-mods/qsl "Quilt Standard Libraries") out!
It's Quilt Standard Libraries / Quilted Fabric API, essential standard libraries for the Quilt :D
