### ISSUE TITLE
Using Mixins where you shouldnt causing potential crashes 1.19.2

### ISSUE THREAD

**Issue by zachsai** [TeamMidnightDust/MidnightLib#31]
![image](https://github.com/TeamMidnightDust/MidnightLib/assets/63996164/f90681e2-fd0e-4db8-a192-6daf58e73e2f)

**Comment by Motschen** [comment]
Duplicate of #19 
This has been fixed in the 1.19.4 version, but so far I haven't had the time to backport it.
