### ISSUE TITLE
(Suggestion) Event when the config is changed from the MidnightConfig screen menu

### ISSUE THREAD

**Issue by Aeldit** [TeamMidnightDust/MidnightLib#34]
An event like this would be useful because in my case for example, I have a Map that contains the values of each options and use it to display different messages and help with the options (mostly on my server-side mods).

The problem here is that when the option is edited via the config screen instead and not via command (ex: `/cyan config <optionName> set true`) the Map is not updated because there is no event that says "Hey, your option have been modified". But I can do it with commands because I update the Map when the value is modified.

When in multiplayer, the options can only be edited via commands so this is not a problem, but on client they have both ways to do it (because of the LAN possibility).

Would this be possible ?
(Sorry for this big block of text but this is to explain the idea correctly)

**Comment by Tschipcraft** [comment]
Duplicate of #33?

**Comment by Aeldit** [comment]
It is indeed a duplicate, so I'm gonna close this
