### ISSUE TITLE
Forge server crashed during startup

### ISSUE THREAD

**Issue by Suel-ki** [TeamMidnightDust/MidnightLib#35]
https://mclo.gs/N8lgUgx#L73

**Comment by Suel-ki** [comment]
The issue should be present at [here](https://github.com/TeamMidnightDust/MidnightLib/blob/f71e8dbdc3139d26a65048b68b9b0532f343cdb2/forge/src/main/java/eu/midnightdust/forge/MidnightLibForge.java#L21C1-L22C131).

**Comment by DumbXBoxAcct** [comment]
Same issue. Forge ver. 47.1.0. and version 1.4.1 of this mod,  Crash log is attached,  Works just fine on the 47.1.0 client, though.
[2023-08-26-1.log](https://github.com/TeamMidnightDust/MidnightLib/files/12447109/2023-08-26-1.log)

**Comment by Bob74** [comment]
Are there plans to fix 1.4.1 version or is it 1.5.x exclusive?

EDIT:
If someone needs it, I've rebuilt the lib from commit https://github.com/TeamMidnightDust/MidnightLib/tree/59989308f63ad8bad4bc3021dff43ad806b49042 to include the forge server fix.

Download : [midnightlib-forge-1.4.1.jar.zip](https://github.com/TeamMidnightDust/MidnightLib/files/12706557/midnightlib-forge-1.4.1.jar.zip)

**Comment by Alexandra-Myers** [comment]
also, I have made a port of 1.5 to 1.20 and 1.20.1, and plan to backport it further as well since I rely on Midnight myself, and providing the best version of it for users is ideal imo

https://github.com/Alexandra-Myers/MidnightLib/releases/tag/1.5.0-1.20-Forge

> Are there plans to fix 1.4.1 version or is it 1.5.x exclusive?
> 
> EDIT: If someone needs it, I've rebuilt the lib from commit https://github.com/TeamMidnightDust/MidnightLib/tree/59989308f63ad8bad4bc3021dff43ad806b49042 to include the forge server fix.
> 
> Download : [midnightlib-forge-1.4.1.jar.zip](https://github.com/TeamMidnightDust/MidnightLib/files/12706557/midnightlib-forge-1.4.1.jar.zip)
