### ISSUE TITLE
Incorrect texture used as config background

### ISSUE THREAD

**Issue by xllifi** [TeamMidnightDust/MidnightLib#39]
Minecraft's world creation uses `light_dirt_background.png`, MidnightLib's config uses `options_background.png`. Both of them use the same tabs
This partially breaks resourcepack compatibility
![mcworldcreation](https://github.com/TeamMidnightDust/MidnightLib/assets/70767436/a4338aad-4de9-4004-8d7e-5e529e7d46d0)
![puzzle](https://github.com/TeamMidnightDust/MidnightLib/assets/70767436/33cbcdab-fa38-456c-8e37-d2b819775779)

**Possible solutions:**
- Use `light_dirt_background.png`
- Add a new texture

**Comment by Motschen** [comment]
The options background texture is used, because these screens contain an options list widget, which uses that as it's background. Changing the texture would require adding our own renderBackground method, which would increase the file size a lot.

**Comment by xllifi** [comment]
Is adding a new tabs and footers texture a better solution then?

**Comment by Motschen** [comment]
> Is adding a new tabs and footers texture a better solution then?

Nope, that'd require even more code.

**Comment by xllifi** [comment]
So there's no fix I guess :(
