### ISSUE TITLE
Due to JitPack trying to build MidnightLib with Java 8, JitPack cannot be used as a source for 0.3.0 as a dependency

### ISSUE THREAD

**Issue by cocona20xx** [TeamMidnightDust/MidnightLib#4]
Basically, JitPack tries to build 0.3.0 with Java 8 instead of Java 16, fails, and then _prevents end users from downloading the mod as a dependency, _as it thinks that the mod cannot be build._ [See the error log from JitPack for more details.](https://jitpack.io/com/github/TeamMidnightDust/MidnightLib/v0.3.0/build.log)

I'm going to see if its possible to force Gradle to use the correct java version in a way that this repo isn't doing in a fork, as well.

**Comment by cocona20xx** [comment]
Tried to use `jitpack.yml` to make jitpack build with java 16 in a forked repo, however it seems like jitpack no longer works properly in that regard, as it did absolutely nothing -.-

**Comment by Motschen** [comment]
JitPack kinda sucks, but you can get the library from the Modrinth maven.
Add this to your repositories: 
`maven {
		url = "https://api.modrinth.com/maven"
	}`

And this to your dependencies:
`modImplementation "maven.modrinth:midnightlib:${project.midnightlib_version}"
include "maven.modrinth:midnightlib:${project.midnightlib_version}"`

And define the version in gradle.properties like this:
`midnightlib_version=0.3.0`

**Comment by cocona20xx** [comment]
thanks a ton, didnt know about that!
