### ISSUE TITLE
MidnightLib fails to load for my server

### ISSUE THREAD

**Issue by Camiom** [TeamMidnightDust/MidnightLib#41]
Recently I tried adding some new QoL and overall content mods to my cobblemon server that I host for my friends.  When I try to run the server I get a greenlight on everything except for the very bottom where it tells me that midnightlib failed to load to the server and then crashes the server.

This is a hastebin of the server starting up: https://hastebin.com/share/zudakezade.perl

This is the crash report: https://hastebin.com/share/uzinokimar.perl

**Comment by Motschen** [comment]
Seems to be the same as #44, closing this one.
