### ISSUE TITLE
Crash upon clicking on "MidnightLib"'s config button in the options settings.

### ISSUE THREAD

**Issue by PlayfulPiano** [TeamMidnightDust/MidnightLib#42]
MC: 1.20.1
Forge: 47.2.4
Using the Better MC 4 v19 Modpack (with modifications), modlist should be shown within the crash report.

[crash-2023-11-06_17.22.37-client.txt](https://github.com/TeamMidnightDust/MidnightLib/files/13273186/crash-2023-11-06_17.22.37-client.txt)

**Comment by Motschen** [comment]
It seems like MidnightLib wasn't able to initialize at all in your modpack, likely due to errors with other mods.
Could you send me the entire minecraft log, please?

**Comment by PlayfulPiano** [comment]
It's been a while and actually iirc it fixed itself. Did do a few mod switches, so I won't be able to reproduce now. Sorry.
