### ISSUE TITLE
1.20.1 Forge Server crash 

### ISSUE THREAD

**Issue by NTCatx** [TeamMidnightDust/MidnightLib#43]
I was wanting to make a server with some friends but one of the mods im really wanting to use uses your mod as a depency, I've gone though and tried remove mulitple mods trying to figure out what is conflicting but removing MidnightLib seem to let the server launch
Here is the Log file from the server: https://pastebin.com/CgFevtdY

**Comment by Motschen** [comment]
Closing this in favor of #44
