### ISSUE TITLE
Suggestion: Support for arrays and non-String lists

### ISSUE THREAD

**Issue by KonSola5** [TeamMidnightDust/MidnightLib#45]
Currently, they sorta work (they show up in config):
![config](https://github.com/TeamMidnightDust/MidnightLib/assets/125081901/1017abec-2cc3-4924-bf9d-68eb4d630278)
... but they don't show up in-game.
![game](https://github.com/TeamMidnightDust/MidnightLib/assets/125081901/3860e38f-f83f-4498-b106-580dab22bb2b)

Lists of other types than String sorta work both in-game and in config:
```java
@Entry(category = "generating") public static List<Double> gourmaryllisList = new ArrayList<>(Arrays.asList(0.0, 1.0, 1.3, 1.5, 1.6, 1.7, 1.75, 1.8));
```
![config](https://github.com/TeamMidnightDust/MidnightLib/assets/125081901/d9c5f735-d651-42d5-9fc4-3f4853a00194)
... but after changing a value, the value gets wrapped with quotation marks.
![config](https://github.com/TeamMidnightDust/MidnightLib/assets/125081901/bd8f2430-bb92-4bba-ba36-e560afc6e4ee)

If the non-String types would be supported, it would save on parsing strings into doubles (or other arbitrary type) on the modder's end.

**Comment by Motschen** [comment]
Added in 1.6.0 :)
