### ISSUE TITLE
If a config file does not contain a list, Minecraft crashes upon an attempt to modify the list

### ISSUE THREAD

**Issue by KonSola5** [TeamMidnightDust/MidnightLib#46]
Using MidnightLib 1.4.1-fabric.

To reproduce:
1. Make a config with a string list.
2. Launch the game and open the config screen.
3. Try to insert something into the textbox.
4. Crash due to UnsupportedOperationException.

5. Launch Minecraft, but this time open the config screen and close it (so that the config file generates).
6. Try to insert something into the textbox.
7. Succeed.

Log: [2023-12-01-7.log](https://github.com/TeamMidnightDust/MidnightLib/files/13531095/2023-12-01-7.log)

**Comment by KonSola5** [comment]
Current workaround: Add `MidnightConfig.write("modid");` below the `MidnightConfig.init("modid", ConfigFile.class)` so that the config file is present and filled.

**Comment by Motschen** [comment]
This seems like an issue on your side.
You need to use an array list instead of a normal one, like this:
`public static List<String> listTest = new ArrayList<>();`

**Comment by Motschen** [comment]
Alternatively, you can use Lists.newArrayList();

**Comment by supersaiyansubtlety** [comment]
this should be updated to use a modifiable list: https://github.com/TeamMidnightDust/MidnightLib/blob/877c787e26909f510ec3e51f09a75f92ee1b2684/src/test/java/eu/midnightdust/test/config/MidnightConfigExample.java#L47
