### ISSUE TITLE
Comment runs off screen

### ISSUE THREAD

**Issue by thomasglasser** [TeamMidnightDust/MidnightLib#48]
![image](https://github.com/TeamMidnightDust/MidnightLib/assets/63979449/18a9b5cd-525a-438f-ba83-67e82cda6ddd)
When a centered comment is too long, it will run off the screen instead of going to a new line. As pictured, using \n just adds the box.

**Comment by Motschen** [comment]
I'll release this soon, along with other bug- and crashfixes, perhaps also some new features :)
