### ISSUE TITLE
Stackoverflow / Crash

### ISSUE THREAD

**Issue by GruenerNinja** [TeamMidnightDust/MidnightLib#49]
[2024-01-28-2.log](https://github.com/TeamMidnightDust/MidnightLib/files/14075796/2024-01-28-2.log)

Minecraft Crashes when i try to open modmeneu but onely if midnightlib is installed it crashes in the log i saw tath it creates a stackoverflow with midnightlib

**Comment by Motschen** [comment]
Seems more like an issue with FancyMenu, rather than MidnightLib.
