### ISSUE TITLE
Enabling `@Comment` components to use complex text

### ISSUE THREAD

**Issue by Jaffe2718** [TeamMidnightDust/MidnightLib#62]
Enables the `@Comment` component to use complex text, such as colored text, italicized text, clickable text, or a composite of these, since language files like `en_us.json` that use `§` cannot produce clickable text.

Like this one:
```java
Text text = Text.translatable("modid.midnightconfig.fieldName").setStyle(Style.EMPTY.withColor(0x00FF00).withClickEvent(new ClickEvent(ClickEvent.Action.OPEN_URL, "https://example.com")));
```

The user can initialize `@Comment` like this:
```java
static final Text text1 = Text.translatable("modid.key.name").setStyle(Style.EMPTY.withColor(0x00FF00).withClickEvent(new ClickEvent(ClickEvent.Action.OPEN_URL, "https://example.com")));
@Comment(category = "custom", text = text1) public static Comment myComment;
```
then the translate key becomes `modid.key.name` instead of the default value `modid.midnightconfig.myComment`

**Comment by Motschen** [comment]
Sadly, this is not possible, due to fields in annotations requiring constant types.
I'll leave this open in case I find another way to do it.

**Comment by Jaffe2718** [comment]
Another question, can you make a kind of `@Entry` specifically for selecting file paths and folder paths?

Like this:
```java
@Entry(category = "config", width = 300, isFile = true) public static String filePath = "";
@Entry(category = "config", width = 300, isDir = true) public static String dirPath = "";
```

**Comment by Jaffe2718** [comment]
I've submitted a PR for you for the FileChooser idea. #63

**Comment by Motschen** [comment]
I just released an updated version with your file chooser PR, as well as many other QoL additions.
