### ISSUE TITLE
[BUG] File Selector UI Renders Wrong Characters （1.6.0)

### ISSUE THREAD

**Issue by Jaffe2718** [TeamMidnightDust/MidnightLib#64]
I found that file chooser with this 1.6.0 official release version of the MidnightLib module gives the following character rendering error:

<img width="1278" alt="s2024-08-25 220500" src="https://github.com/user-attachments/assets/1659c06d-8527-45cc-819f-bf10d8747257">

I remember I didn't have this error before when I added the FileChooser feature and sent you a PR #63:

<img width="1270" alt="s2024-08-25 215107" src="https://github.com/user-attachments/assets/892dcb2e-f7cc-4a9e-8232-1e5cb1dbf447">

From the interface it looks like the reset button is optimized, it should be after commit [Improved layout and lists](https://github.com/TeamMidnightDust/MidnightLib/commit/3e20b904b76f7a343b655b0605028e1b317a89f7). In the next commit [Show errors again and correctly handle closing](https://github.com/TeamMidnightDust/MidnightLib/commit/5fa635911f2c2441a19c5ec8e141a907da90c763) you rename the `functionButton` to `actionButton`. So I think this one is incorrectly rendering the color block of `colorButton`.

**Comment by Motschen** [comment]
This is just a side effect of the box being smaller. The character disappears when clicking into the field.

**Comment by Jaffe2718** [comment]
> This is just a side effect of the box being smaller. The character disappears when clicking into the field.

I rechecked the code and it really doesn't seem to be a problem with the module code, it's supposed to be a bug in Mojang's writing of Minecraft.
