### ISSUE TITLE
MidnightLib causes freeze/black screen

### ISSUE THREAD

**Issue by Jab125** [TeamMidnightDust/MidnightLib#67]
Issue is present in 1.6.0-1.6.1
It is not present in 1.5.8
Context:
macOS 14.2
Mac Mini M2 (2023)

Related Issue: https://github.com/ViolaFlower/Re-Console/issues/130

**Comment by Jab125** [comment]
I suspect it was caused by https://github.com/TeamMidnightDust/MidnightLib/commit/fbde598420ae51ed7b4f22b290fa834ab2eda359#diff-c857031be4bbf9337f8338e5fcbf18c0c54b784c77672d112b0916076e389c88 (#63)

**Comment by Jab125** [comment]
Another way to get a file dialog: https://javadoc.lwjgl.org/org/lwjgl/util/nfd/NativeFileDialog.html

**Comment by Motschen** [comment]
That's a pretty severe issue.
Would you be so kind and test if this build fixes it (unzip the archive):
[midnightlib-fabric-1.6.2-test.1.zip](https://github.com/user-attachments/files/16839336/midnightlib-fabric-1.6.2-test.1.zip)
I unfortunately don't own a Mac myself, so I cannot test it.

**Comment by Motschen** [comment]
Please lmk if the fix worked.

**Comment by Jab125** [comment]
> That's a pretty severe issue.
> 
> Would you be so kind and test if this build fixes it (unzip the archive):
> 
> [midnightlib-fabric-1.6.2-test.1.zip](https://github.com/user-attachments/files/16839336/midnightlib-fabric-1.6.2-test.1.zip)
> 
> I unfortunately don't own a Mac myself, so I cannot test it.

The main problem is that AWT doesn't work on macOS if LWJGL is used, so turning off headless breaks it

**Comment by Motschen** [comment]
Alright, I think this should work now, please test if it does:
[midnightlib-fabric-1.6.3-test.1.zip](https://github.com/user-attachments/files/16874944/midnightlib-fabric-1.6.3-test.1.zip)
