### ISSUE TITLE
Using MidnightLib in Architectury project

### ISSUE THREAD

**Issue by rarepeepo** [TeamMidnightDust/MidnightLib#74]
Hi,

I'm using [Architectury](https://docs.architectury.dev/loom/introduction) to target both `Forge` and `Fabric` and I was wondering how I would go about using `MidnightLib` in that setup.

More specifically, how would I reference the library from the shared `common` project so that I can put my annotated Config class and the call to `MidnightConfig.init` in there.

I understand I have to add a reference to the `dependencies` section of the `build.gradle` file in the `common` directory but yea obviously I cannot reference the forge or fabric specific library from that (I think?).

Thanks

**Comment by Motschen** [comment]
You can just add the fabric version as "modCompileOnly" to the common project's build.gradle :)

**Comment by rarepeepo** [comment]
great, thank you!
