### ISSUE TITLE
Update to support 1.21.4

### ISSUE THREAD

**Issue by Patbox** [TeamMidnightDust/MidnightLib#75]
Sadly, even through Mojang didn't as many changes this time, 1.21.3 version doesn't work correctly due to intermediary method changing (haven't checked the reason, through I imagine it's them implementing an interface or something). It crashes when opening mod specific settings. Rest seems to work fine.

Tested with SleepWarp, which 1.21.3 version ran just fine on 1.21.4 excluding that. I patched it with mixin to make it just work for my own usage, but full/official update will be needed at some point.

**Comment by Motschen** [comment]
It was a pretty trivial update, just needed to rename some method references.
Thanks for notifying me!
